import React, { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Alert, RefreshControl, ScrollView, StatusBar, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { notificationService } from "../services/notificationService";

const ICONS={PAYMENT_CONFIRMED:"card-outline",GOODS_RELEASED:"cube-outline",FLAGGED:"warning-outline",CASE_ASSIGNED:"person-add-outline",CASE_RESOLVED:"checkmark-done-outline",EVIDENCE_REQUESTED:"document-attach-outline",TARIFF_UPDATED:"stats-chart-outline",DECLARATION_READY:"document-text-outline",DECLARATION_CLAIMED:"download-outline"};
const formatTime=(value)=>{if(!value)return "";const date=new Date(value);return Number.isNaN(date.getTime())?"":date.toLocaleString();};

export default function Notifications(){
  const router=useRouter(); const [items,setItems]=useState([]); const [unread,setUnread]=useState(0); const [loading,setLoading]=useState(true); const [refreshing,setRefreshing]=useState(false); const [busy,setBusy]=useState(false);
  const load=useCallback(async({refresh=false}={})=>{refresh?setRefreshing(true):setLoading(true);try{const [list,count]=await Promise.all([notificationService.getAll({limit:100,orderBy:"createdAt",orderDirection:"DESC"}),notificationService.getUnreadCount()]);setItems(list.notifications||[]);setUnread(count.unreadCount||0);}catch(error){Alert.alert("Notifications unavailable",error.message||"Unable to load notifications.");}finally{setLoading(false);setRefreshing(false);}},[]);
  useEffect(()=>{load();},[load]);
  const open=async(item)=>{try{if(!item.isRead){await notificationService.markAsRead(item.id);setItems(current=>current.map(value=>value.id===item.id?{...value,isRead:true}:value));setUnread(value=>Math.max(0,value-1));}const id=item.data?.declarationId;if(id){router.push({pathname:item.type==="FLAGGED"||item.type==="CASE_ASSIGNED"?"/flagged-declaration-details":"/declaration-details",params:{id}});}}catch(error){Alert.alert("Unable to open",error.message||"Unable to update this notification.");}};
  const markAll=async()=>{if(!unread||busy)return;setBusy(true);try{await notificationService.markAllAsRead();setItems(current=>current.map(item=>({...item,isRead:true})));setUnread(0);}catch(error){Alert.alert("Update failed",error.message);}finally{setBusy(false);}};
  const remove=(item)=>Alert.alert("Delete notification",`Delete “${item.title}”?`,[{text:"Cancel",style:"cancel"},{text:"Delete",style:"destructive",onPress:async()=>{try{await notificationService.deleteOne(item.id);setItems(current=>current.filter(value=>value.id!==item.id));if(!item.isRead)setUnread(value=>Math.max(0,value-1));}catch(error){Alert.alert("Delete failed",error.message);}}}]);
  const clearAll=()=>items.length&&Alert.alert("Clear notifications","Delete all notifications?",[{text:"Cancel",style:"cancel"},{text:"Delete all",style:"destructive",onPress:async()=>{setBusy(true);try{await notificationService.deleteAll();setItems([]);setUnread(0);}catch(error){Alert.alert("Delete failed",error.message);}finally{setBusy(false);}}}]);
  return <View style={s.container}><StatusBar translucent backgroundColor="transparent" barStyle="dark-content"/><SafeAreaView style={s.safe}><View style={s.header}><TouchableOpacity onPress={()=>router.back()} style={s.headerBtn}><Ionicons name="arrow-back" size={24} color="#171725"/></TouchableOpacity><View><Text style={s.title}>Notifications</Text><Text style={s.subtitle}>{unread} unread</Text></View><TouchableOpacity onPress={clearAll} style={s.headerBtn} disabled={!items.length||busy}><Ionicons name="trash-outline" size={21} color={items.length?"#EF4444":"#C7CDD1"}/></TouchableOpacity></View>
  <View style={s.actions}><Text style={s.count}>{items.length} notifications</Text><TouchableOpacity onPress={markAll} disabled={!unread||busy}><Text style={[s.markAll,!unread&&s.disabled]}>Mark all as read</Text></TouchableOpacity></View>
  <ScrollView style={s.list} contentContainerStyle={s.listContent} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>load({refresh:true})} tintColor="#F5B81B"/>}>{loading?<ActivityIndicator color="#F5B81B" style={s.loader}/>:items.length===0?<View style={s.empty}><View style={s.emptyIcon}><Ionicons name="notifications-off-outline" size={34} color="#78828A"/></View><Text style={s.emptyTitle}>No notifications</Text><Text style={s.emptyCopy}>Updates about declarations and investigations will appear here.</Text></View>:items.map(item=><TouchableOpacity key={item.id} style={[s.card,!item.isRead&&s.unread]} onPress={()=>open(item)} onLongPress={()=>remove(item)} activeOpacity={.82}><View style={[s.icon,!item.isRead&&s.iconUnread]}><Ionicons name={ICONS[item.type]||"notifications-outline"} size={21} color="#171725"/></View><View style={s.body}><View style={s.cardTop}><Text style={s.cardTitle}>{item.title}</Text>{!item.isRead&&<View style={s.dot}/>}</View><Text style={s.message}>{item.message}</Text><Text style={s.time}>{formatTime(item.createdAt)}</Text></View><TouchableOpacity onPress={()=>remove(item)} style={s.delete}><Ionicons name="close" size={18} color="#9CA3AF"/></TouchableOpacity></TouchableOpacity>)}</ScrollView></SafeAreaView></View>;
}
const s=StyleSheet.create({container:{flex:1,backgroundColor:"#F7F7F9"},safe:{flex:1},header:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",paddingHorizontal:16,paddingVertical:10,backgroundColor:"#FFF",borderBottomWidth:1,borderBottomColor:"#ECEEF0"},headerBtn:{width:42,height:42,alignItems:"center",justifyContent:"center"},title:{fontSize:19,fontWeight:"800",color:"#171725",textAlign:"center"},subtitle:{fontSize:11,color:"#78828A",textAlign:"center"},actions:{flexDirection:"row",justifyContent:"space-between",paddingHorizontal:20,paddingVertical:13},count:{fontSize:12,color:"#78828A"},markAll:{fontSize:12,fontWeight:"700",color:"#B27B00"},disabled:{color:"#BFC5C9"},list:{flex:1},listContent:{paddingHorizontal:16,paddingBottom:40,gap:10},loader:{marginTop:60},card:{flexDirection:"row",alignItems:"flex-start",padding:14,borderRadius:14,borderWidth:1,borderColor:"#E4E7EB",backgroundColor:"#FFF",gap:11},unread:{backgroundColor:"#FFFCF1",borderColor:"#F5D77B"},icon:{width:42,height:42,borderRadius:21,backgroundColor:"#F1F3F5",alignItems:"center",justifyContent:"center"},iconUnread:{backgroundColor:"#F5B81B"},body:{flex:1,gap:4},cardTop:{flexDirection:"row",alignItems:"center",gap:8},cardTitle:{flex:1,fontSize:13,fontWeight:"700",color:"#171725"},dot:{width:8,height:8,borderRadius:4,backgroundColor:"#F5B81B"},message:{fontSize:12,lineHeight:17,color:"#4B5563"},time:{fontSize:10,color:"#9CA3AF",marginTop:2},delete:{padding:3},empty:{alignItems:"center",padding:48,gap:9},emptyIcon:{width:70,height:70,borderRadius:35,backgroundColor:"#ECEFF1",alignItems:"center",justifyContent:"center"},emptyTitle:{fontSize:17,fontWeight:"700",color:"#171725"},emptyCopy:{fontSize:12,lineHeight:18,color:"#78828A",textAlign:"center"}});
