import React, { useState } from "react";
import { ActivityIndicator, Alert, KeyboardAvoidingView, Platform, ScrollView, StatusBar, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { declarationService, formatUsd, getDeclarationStatusLabel } from "../services/declarationService";

const Row=({label,value,last})=><View style={[s.row,!last&&s.rowBorder]}><Text style={s.rowLabel}>{label}</Text><Text style={s.rowValue}>{value}</Text></View>;
export default function RequestDeclaration(){const router=useRouter();const [ucr,setUcr]=useState("");const [result,setResult]=useState(null);const [busy,setBusy]=useState(false);const search=async()=>{const value=ucr.trim();if(value.length<5||busy)return;setBusy(true);setResult(null);try{const response=await declarationService.getByUcr(value);setResult(response.declaration);}catch(error){Alert.alert("Declaration not found",error.message||"Unable to find this UCR.");}finally{setBusy(false);}};const open=()=>result&&router.push({pathname:result.status==="FLAGGED"||result.status==="UNDER_INVESTIGATION"?"/flagged-declaration-details":"/declaration-details",params:{id:result.declarationId}});return <View style={s.container}><StatusBar translucent backgroundColor="transparent" barStyle="dark-content"/><SafeAreaView style={s.safe}><View style={s.header}><TouchableOpacity style={s.back} onPress={()=>router.back()}><Ionicons name="arrow-back" size={24} color="#171725"/></TouchableOpacity><Text style={s.headerTitle}>Find Declaration</Text><View style={s.back}/></View><KeyboardAvoidingView style={s.safe} behavior={Platform.OS==="ios"?"padding":"height"}><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><View><Text style={s.title}>Search by UCR</Text><Text style={s.copy}>Enter the Unique Consignment Reference to retrieve the declaration.</Text></View><View style={s.search}><Ionicons name="search" size={20} color="#78828A"/><TextInput style={s.input} placeholder="2026-ICUMS-0004" placeholderTextColor="#9CA3AF" value={ucr} onChangeText={setUcr} autoCapitalize="characters" autoCorrect={false} returnKeyType="search" onSubmitEditing={search}/></View><TouchableOpacity style={[s.button,ucr.trim().length<5&&s.disabled]} onPress={search} disabled={ucr.trim().length<5||busy}>{busy?<ActivityIndicator color="#000"/>:<Text style={s.buttonText}>Find declaration</Text>}</TouchableOpacity>{result&&<View style={s.card}><View style={s.cardHeader}><View><Text style={s.declarationId}>{result.declarationId}</Text><Text style={s.ucr}>{result.ucr}</Text></View><View style={s.status}><Text style={s.statusText}>{getDeclarationStatusLabel(result.status)}</Text></View></View><Row label="Product" value={result.productDescription}/><Row label="HS Code" value={result.hsCode}/><Row label="Declared Value" value={formatUsd(result.declaredValueUSD)}/><Row label="Duty Calculated" value={formatUsd(result.dutyCalculatedUSD)}/><Row label="Customs Officer" value={result.customsOfficer?.fullName||"Unassigned"} last/><TouchableOpacity style={s.openButton} onPress={open}><Text style={s.openText}>Open declaration</Text><Ionicons name="arrow-forward" size={18} color="#171725"/></TouchableOpacity></View>}</ScrollView></KeyboardAvoidingView></SafeAreaView></View>}
const s=StyleSheet.create({container:{flex:1,backgroundColor:"#F7F7F9"},safe:{flex:1},header:{height:62,backgroundColor:"#FFF",borderBottomWidth:1,borderBottomColor:"#ECEEF0",flexDirection:"row",alignItems:"center",justifyContent:"space-between",paddingHorizontal:14},back:{width:42,height:42,alignItems:"center",justifyContent:"center"},headerTitle:{fontSize:18,fontWeight:"800",color:"#171725"},content:{padding:20,paddingBottom:40,gap:15},title:{fontSize:23,fontWeight:"800",color:"#171725"},copy:{fontSize:13,lineHeight:19,color:"#78828A",marginTop:5},search:{height:54,borderRadius:12,borderWidth:1,borderColor:"#E4E7EB",backgroundColor:"#FFF",flexDirection:"row",alignItems:"center",paddingHorizontal:14,gap:10},input:{flex:1,fontSize:14,color:"#171725"},button:{height:52,borderRadius:11,backgroundColor:"#F5B81B",alignItems:"center",justifyContent:"center"},disabled:{opacity:.45},buttonText:{fontSize:15,fontWeight:"700",color:"#000"},card:{backgroundColor:"#FFF",borderRadius:13,borderWidth:1,borderColor:"#E4E7EB",padding:15,marginTop:8},cardHeader:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",paddingBottom:10},declarationId:{fontSize:15,fontWeight:"800",color:"#171725"},ucr:{fontSize:11,color:"#78828A",marginTop:2},status:{backgroundColor:"#FFF7DA",paddingHorizontal:10,paddingVertical:5,borderRadius:12},statusText:{fontSize:11,fontWeight:"700",color:"#8A6200"},row:{flexDirection:"row",justifyContent:"space-between",paddingVertical:11,gap:14},rowBorder:{borderBottomWidth:1,borderBottomColor:"#F0F1F2"},rowLabel:{fontSize:12,color:"#78828A",flex:1},rowValue:{fontSize:12,fontWeight:"600",color:"#171725",textAlign:"right",flex:1.5},openButton:{height:46,borderRadius:10,borderWidth:1,borderColor:"#F5B81B",flexDirection:"row",alignItems:"center",justifyContent:"center",gap:8,marginTop:12},openText:{fontSize:13,fontWeight:"700",color:"#171725"}});
