import React, { useState } from "react";
import { ActivityIndicator, Alert, KeyboardAvoidingView, Platform, ScrollView, StatusBar, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { authService } from "../services/authService";

const PasswordInput=({label,value,onChangeText,visible,onToggle})=><View style={s.field}><Text style={s.label}>{label}</Text><View style={s.inputWrap}><Ionicons name="lock-closed-outline" size={18} color="#78828A"/><TextInput style={s.input} value={value} onChangeText={onChangeText} secureTextEntry={!visible} autoCapitalize="none"/><TouchableOpacity onPress={onToggle}><Ionicons name={visible?"eye-outline":"eye-off-outline"} size={20} color="#78828A"/></TouchableOpacity></View></View>;
export default function Security(){const router=useRouter();const [oldPassword,setOldPassword]=useState("");const [newPassword,setNewPassword]=useState("");const [confirm,setConfirm]=useState("");const [visible,setVisible]=useState({old:false,next:false,confirm:false});const [busy,setBusy]=useState(false);const valid=oldPassword.length>0&&newPassword.length>=6&&newPassword===confirm;const submit=async()=>{if(!valid||busy)return;setBusy(true);try{const response=await authService.changePassword({oldPassword,newPassword});Alert.alert("Password changed",response.message||"Your password was updated.",[{text:"Done",onPress:()=>router.back()}]);setOldPassword("");setNewPassword("");setConfirm("");}catch(error){Alert.alert("Change failed",error.message||"Unable to change your password.");}finally{setBusy(false);}};return <View style={s.container}><StatusBar translucent backgroundColor="transparent" barStyle="dark-content"/><SafeAreaView style={s.safe}><View style={s.header}><TouchableOpacity style={s.back} onPress={()=>router.back()}><Ionicons name="arrow-back" size={24} color="#171725"/></TouchableOpacity><Text style={s.headerTitle}>Security</Text><View style={s.back}/></View><KeyboardAvoidingView style={s.safe} behavior={Platform.OS==="ios"?"padding":"height"}><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><View style={s.hero}><View style={s.shield}><Ionicons name="shield-checkmark-outline" size={32} color="#171725"/></View><Text style={s.title}>Change password</Text><Text style={s.copy}>Use a password you do not use elsewhere.</Text></View><View style={s.card}><PasswordInput label="Current password" value={oldPassword} onChangeText={setOldPassword} visible={visible.old} onToggle={()=>setVisible(v=>({...v,old:!v.old}))}/><PasswordInput label="New password" value={newPassword} onChangeText={setNewPassword} visible={visible.next} onToggle={()=>setVisible(v=>({...v,next:!v.next}))}/><PasswordInput label="Confirm new password" value={confirm} onChangeText={setConfirm} visible={visible.confirm} onToggle={()=>setVisible(v=>({...v,confirm:!v.confirm}))}/><View style={s.rules}><Text style={[s.rule,newPassword.length>=6&&s.valid]}>At least 6 characters</Text><Text style={[s.rule,confirm&&newPassword===confirm&&s.valid]}>Passwords match</Text></View><TouchableOpacity style={[s.button,!valid&&s.disabled]} onPress={submit} disabled={!valid||busy}>{busy?<ActivityIndicator color="#000"/>:<Text style={s.buttonText}>Update password</Text>}</TouchableOpacity></View></ScrollView></KeyboardAvoidingView></SafeAreaView></View>}
const s=StyleSheet.create({container:{flex:1,backgroundColor:"#F7F7F9"},safe:{flex:1},header:{height:62,backgroundColor:"#FFF",borderBottomWidth:1,borderBottomColor:"#ECEEF0",flexDirection:"row",alignItems:"center",justifyContent:"space-between",paddingHorizontal:14},back:{width:42,height:42,alignItems:"center",justifyContent:"center"},headerTitle:{fontSize:18,fontWeight:"800",color:"#171725"},content:{padding:20,paddingBottom:40,gap:20},hero:{alignItems:"center",gap:7,paddingVertical:12},shield:{width:64,height:64,borderRadius:32,backgroundColor:"#F5B81B",alignItems:"center",justifyContent:"center"},title:{fontSize:22,fontWeight:"800",color:"#171725"},copy:{fontSize:13,color:"#78828A"},card:{backgroundColor:"#FFF",borderRadius:14,borderWidth:1,borderColor:"#E4E7EB",padding:17,gap:16},field:{gap:7},label:{fontSize:12,fontWeight:"700",color:"#4B5563"},inputWrap:{height:52,borderWidth:1,borderColor:"#E4E7EB",borderRadius:11,flexDirection:"row",alignItems:"center",paddingHorizontal:13,gap:10},input:{flex:1,fontSize:14,color:"#171725"},rules:{gap:5},rule:{fontSize:11,color:"#9CA3AF"},valid:{color:"#4CAF50"},button:{height:52,borderRadius:11,backgroundColor:"#F5B81B",alignItems:"center",justifyContent:"center"},disabled:{opacity:.45},buttonText:{fontSize:15,fontWeight:"700",color:"#000"}});
